services:
  _defaults:
    autowire: true
    autoconfigure: true

  #
  # Data Provider
  #

  Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Assets:
    class: Pimcore\Bundle\SimpleBackendSearchBundle\DataProvider\GDPR\Assets
    arguments:
      $config: '%pimcore.gdpr-data-extrator.assets%'

  Pimcore\Bundle\AdminBundle\GDPR\DataProvider\DataObjects:
    class: Pimcore\Bundle\SimpleBackendSearchBundle\DataProvider\GDPR\DataObjects
    arguments:
      $config: '%pimcore.gdpr-data-extrator.dataobjects%'
